"""
@Brief: Channels for video transmission.
"""

import os
import random
import numpy as np
import scipy.io as scio
import matplotlib.pyplot as plt


class Channel(object):
    """
    :brief: Channel class for reading reserved MIMO channels generated by Quadriga.
    You can refer to the user manual of Quadriga to learn how to generate channels.
    """
    def __int__(self):
        # self.matlab_ch_dir = matlab_ch_dir
        pass

    def gen_ch_2_2_UMi_NLOS(self):
        index = random.randint(0, len(os.listdir("./UMi_NLOS_2_2"))-1) 
        print("Current channel index:", index)

        ch = scio.loadmat("./UMi_NLOS_2_2/{}.mat".format(index))
        H_freq = np.transpose(np.transpose(ch['H_freq'], (2, 1, 0)), (0, 2, 1))  # Nf×Nr×Nt

        return H_freq

    def gen_ch_2_2_UMa_NLOS(self):
        index = random.randint(0, len(os.listdir("./UMa_NLOS_2_2"))-1) 
        print("Current channel index:", index)

        ch = scio.loadmat("./UMa_NLOS_2_2/{}.mat".format(index))
        H_freq = np.transpose(np.transpose(ch['H_freq'], (2, 1, 0)), (0, 2, 1))  # Nf×Nr×Nt

        return H_freq

    def gen_ch_2_2_RMa_NLOS(self):
        index = random.randint(0, len(os.listdir("./RMa_NLOS_2_2"))-1)  
        print("Current channel index:", index)

        ch = scio.loadmat("./RMa_NLOS_2_2/{}.mat".format(index))
        H_freq = np.transpose(np.transpose(ch['H_freq'], (2, 1, 0)), (0, 2, 1))  # Nf×Nr×Nt

        return H_freq

    def gen_ch_2_2_Indoor(self):
        index = random.randint(0, len(os.listdir("./Indoor_Open_Office_2_2"))-1) 
        print("Current channel index:", index)

        ch = scio.loadmat("./Indoor_Open_Office_2_2/{}.mat".format(index))
        H_freq = np.transpose(np.transpose(ch['H_freq'], (2, 1, 0)), (0, 2, 1))  # Nf×Nr×Nt

        return H_freq

    def gen_ch_2_2_OTA(self, index):
        # OTA channels
        H11_filename = '../OTA/OTA_dataset/SRM/H11/'+str(index)+'.txt'
        H21_filename = '../OTA/OTA_dataset/SRM/H21/' + str(index) + '.txt'
        H12_filename = '../OTA/OTA_dataset/SRM/H12/' + str(index) + '.txt'
        H22_filename = '../OTA/OTA_dataset/SRM/H22/' + str(index) + '.txt'
        with open(H11_filename, 'r') as file:
            count = 1
            H11_ = np.array([])
            while count <= 250:
                line = file.readline()
                if 32 <= count <= 95 or 157 <= count <= 220:
                    H11_ = np.append(H11_, np.array([float(line)]))
                count += 1
            H11 = H11_[0:64] + 1j * H11_[64:]
        with open(H21_filename, 'r') as file:
            count = 1
            H21_ = np.array([])
            while count <= 250:
                line = file.readline()
                if 32 <= count <= 95 or 157 <= count <= 220:
                    H21_ = np.append(H21_, np.array([float(line)]))
                count += 1
            H21 = H21_[0:64] + 1j * H21_[64:]
        with open(H12_filename, 'r') as file:
            count = 1
            H12_ = np.array([])
            while count <= 250:
                line = file.readline()
                if 32 <= count <= 95 or 157 <= count <= 220:
                    H12_ = np.append(H12_, np.array([float(line)]))
                count += 1
            H12 = H12_[0:64] + 1j * H12_[64:]
        with open(H22_filename, 'r') as file:
            count = 1
            H22_ = np.array([])
            while count <= 250:
                line = file.readline()
                if 32 <= count <= 95 or 157 <= count <= 220:
                    H22_ = np.append(H22_, np.array([float(line)]))
                count += 1
            H22 = H22_[0:64] + 1j * H22_[64:]

        H_freq = np.stack((np.stack((H11, H21)), np.stack((H12, H22))), axis=1)
        H_freq = np.transpose(H_freq, (2, 1, 0))  # Nt×Nr×Nf ---> Nf×Nr×Nt

        return H_freq


if __name__ == "__main__":

    chan = Channel()


